# Generated by Django 5.0.1 on 2024-03-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
