# Generated by Django 5.0.1 on 2024-03-29 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_profile_fallowers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="fallowers",
            new_name="followers",
        ),
    ]
