# Generated by Django 5.0.3 on 2024-03-30 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_profile_favorite_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="favorite_comments",
            new_name="favorite_articles",
        ),
    ]
